import { describe, expect, it, vi } from "vitest"

// next/font/google requires network access to fetch font files at build time,
// which isn't available (and isn't the point) in a unit test that only cares
// about the `metadata` export sitting alongside the font calls in this file.
vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "--font-geist" }),
  JetBrains_Mono: () => ({ variable: "--font-jetbrains-mono" }),
}))

const { metadata } = await import("./layout")

describe("root metadata", () => {
  it("titles the product Datalize, not the create-next-app scaffold", () => {
    expect(metadata.title).not.toBe("Create Next App")

    const title = metadata.title
    const defaultTitle =
      typeof title === "object" && title !== null && "default" in title ? title.default : title

    expect(defaultTitle).toBe("Datalize")
  })

  it('templates child route titles as "<page> · Datalize"', () => {
    const title = metadata.title
    const template =
      typeof title === "object" && title !== null && "template" in title ? title.template : null

    expect(template).toBe("%s · Datalize")
  })

  it("describes the product, not the scaffold generator", () => {
    expect(metadata.description).not.toBe("Generated by create next app")
    expect(metadata.description).toBeTruthy()
  })
})
